[package]
name = "video-frame-extraction"
version = "1.0.0"
edition = "2024"

[dependencies]
eframe = "0.32.0"
egui = { version = "0.32.0" }
video-rs = { version = "0.10", features = ["ndarray"] }
ndarray = "0.16"
image = "0"